version: '3.3'
services:
    blockchain:
        tty: true
        volumes:
            - ../files:/src/files/
        ports:
            - "5000:5000"
        build:
            context: ../
            dockerfile: ./docker/Dockerfile

